// Made by CookieCore

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "Terminal.generated.h"



DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FTextUpdateSignature, FString, Text);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FTextWriteLineSignature, FString, Text);

struct FKey;

struct FTerminalHistory
{

	TArray<FString> Lines;
	int32 CurrentIndex = 0;
	FString CurrentLine;

	void Add(const FString& Line)
	{
		Lines.Add(Line);
		CurrentIndex = Lines.Num();
	}

	void SetIndexToLast()
	{
		CurrentIndex = Lines.Num();
	}

	FString GetPrevious()
	{
		if (CurrentIndex > 0)
		{
			CurrentIndex--;
		}
		return CurrentIndex < Lines.Num() ? Lines[CurrentIndex] : FString();
	}

	FString GetNext()
	{
		if (CurrentIndex < Lines.Num())
		{
			CurrentIndex++;
		}
		return CurrentIndex < Lines.Num() ? Lines[CurrentIndex] : CurrentLine;
	}
};

UCLASS(ClassGroup = (Custom), meta = (BlueprintSpawnableComponent))
class TERMINSEEK_API UTerminal : public UActorComponent
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable, Category = "Terminal")
	FTextUpdateSignature TextUpdated;

	UPROPERTY(BlueprintAssignable, Category = "Terminal")
	FTextWriteLineSignature TextWriteLine;

	UFUNCTION(BlueprintCallable, BlueprintPure)
	FString GetScreenText() const;

	UFUNCTION(BlueprintCallable)
	void ActivateTerminal();

	UFUNCTION(BlueprintCallable)
	void DeactivateTerminal() const;

	void PrintLine(const FString& Line);

	UFUNCTION(BlueprintCallable)
	void ClearScreen();

protected:
	// Called when the game starts
	virtual void BeginPlay() override;

private:
	void OnKeyDown(FKey Key);
	TArray<FString> WrapLines(const TArray<FString>& Lines) const;
	void Truncate(TArray<FString>& Lines) const;
	FString JoinWithNewline(const TArray<FString>& Lines) const;
	void AcceptInputLine();
	void Backspace();
	void UpKey();
	void DownKey();
	FString GetKeyString(FKey Key) const;
	void UpdateCurrentTextLine();
	void WriteLine(FString& Line);


	UPROPERTY(EditAnywhere)
	int32 MaxLines = 10;

	UPROPERTY(EditAnywhere)
	int32 MaxColumns = 70;

	FString InputLine;

	int32 PressedBindingIndex;
	int32 RepeatBindingIndex;

	FTerminalHistory TerminalHistory;

public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	TArray<FString> TrainTerminalWords = {
		"abandoned",
		"abnormal",
		"absurdly",
		"accident",
		"accusing",
		"adapting",
		"addicted",
		"adhesive",
		"admitted",
		"advising",
		"affected",
		"affluent",
		"agencies",
		"airplane",
		"alarming",
		"alcoholi",
		"alliance",
		"allowing",
		"aluminum",
		"amateurs",
		"amending",
		"amputate",
		"analyzer",
		"ancestor",
		"angriest",
		"animated",
		"annually",
		"anointed",
		"anterior",
		"antiques",
		"anything",
		"aperture",
		"apparent",
		"applying",
		"appraise",
		"archived",
		"arguably",
		"arrogant",
		"artistic",
		"asbestos",
		"aspirant",
		"assorted",
		"assuring",
	"Bedevils",
	"Bedizens",
	"Begotten",
	"Believed",
	"Belonged",
	"Benching",
	"Benefits",
	"Bestowal",
	"Betaking",
	"Bewaring",
	"Bewilder",
	"Birdcage",
	"Birdseed",
	"Biscuits",
	"Bizarrely",
	"Blackout",
	"Blastoff",
	"Blending",
	"Blossoms",
	"Bluebell",
	"Bluebird",
	"Blueprint",
	"Blurring",
	"Boasting",
	"Bobsleds",
	"Bodysuit",
	"Bogeyman",
	"Bohemian",
	"Boldface",
	"Bombards",
	"Bookcase",
	"Bookends",
	"Bookings",
	"Bookmark",
	"Bookworm",
	"Bounties",
	"Boycotts",
	"Brackets",
	"Bragging",
	"Brainiac",
	"Brainwash",
	"Branches",
	"Brandish",
	"Bratwurst",
	"Breached",
	"Breakage",
	"Breasted",
	"Brethren",
	"Briefing",
	"Brigades",
	"Bristles",
	"Brittle",
	"Brochure",
	"Bromides",
	"Brotherly",
	"Browsees",
	"Browsing",
	"Bucklers",
	"Buddings",
	"Bullhorn",
	"Bullring",
	"Bullwhip",
	"Bumbling",
	"Bundling",
	"Buoyancy",
	"Bypasses",
	"Byzantine",
	"Cabarets",
	"Cadavers",
	"Calamity",
	"Calcined",
	"Callings",
	"Calmness",
	"Campfire",
	"Candelas",
	"Candidate",
	"Canister",
	"Cannibal",
	"Canoeist",
	"Canopies",
	"Captains",
	"Captives",
	"Carapace",
	"Carcasses",
	"Cardigan",
	"Careless",
	"Carriage",
	"Carrying",
	"Cartload",
	"Casebook",
	"Casement",
	"Castings",
	"Castrate",
	"Catapult",
	"Catbirds",
	"Category",
	"Cathodes",
	"Cautious",
	"Cavities",
	"Celibacy",
	"Cemented",
	"Centaurs",
	"Cerebral",
	"Ceremony",
	"Chainman",
	"Chainsaw",
	"Chairmen",
	"Chamomile",
	"Champion",
	"Changeup",
	"Charades",
	"Charcoal",
	"Charring",
	"Chastity",
	"Chattels",
	"Cheapest",
	"Chemical",
	"Cherries",
	"Chestnut",
	"Chevrons",
	"Chicanes",
	"Chieftain",
	"Children",
	"Chilling",
	"Chintzes",
	"Chiseled",
	"Choicest",
	"Choppers",
	"Chorales",
	"Chortles",
	"Christen",
	"Chromium",
	"Chubbier",
	"Churchly",
	"Churning",
	"Ciliated",
	"Cindered",
	"Circlets",
	"Civilian",
	"Civilize",
	"Clamming",
	"Clanging",
	"Clappers",
	"Clashing",
	"Clasping",
	"Cleaning",
	"Clearing",
	"Clerical",
	"Climates",
	"Clipping",
	"Clocking",
	"Cloddish",
	"Cloister",
	"Clonally",
	"Closings",
	"Clothing",
	"Clotting",
	"Clotures",
	"Clubbing",
	"Clueless",
	"Clusters",
	"Clutched",
	"Coalesce",
	"Coasting",
	"Coauthor",
	"Cobbling",
	"Coccyxes",
	"Cockades",
	"Cockiest",
	"Cockpits",
	"Coconuts",
	"Codified",
	"Codifies",
	"Coercing",
	"Coexisted",
	"Coffined",
	"Coinages",
	"Coincide",
	"Coinvent",
	"Colander",
	"Collated",
	"Colleague",
	"Collided",
	"Colliege",
	"Colliers",
	"Collings",
	"Colluded",
	"Colonies",
	"Coloring",
	"Columbia",
	"Columbic",
	"Comatose",
	"Combined",
	"Combines",
	"Comedian",
	"Comforts",
	"Commando",
	"Commence",
	"Commented",
	"Commerse",
	"Commiser",
	"Commited",
	"Committed",
	"Commodity",
	"Commoner",
	"Communes",
	"Commutes",
	"Company",
	"Complain",
	"Complete",
	"Complied",
	"Composer",
	"Compound",
	"Comprise",
	"Comrades",
	"Conceded",
	"Conceive",
	"Conclude",
	"Concrete",
	"Condemns",
	"Condense",
	"Condones",
	"Conduces",
	"Confined",
	"Confines",
	"Confirmatory",
	"Confirms",
	"Conflicted",
	"Confront",
	"Confused",
	"Confutes",
	"Congenial",
	"Congests",
	"Congloms",
	"Congress",
	"Conjoint",
	"Conjured",
	"Connotes",
	"Conquers",
	"Consents",
	"Conserve",
	"Consider",
	"Consigns",
	"Consists",
	"Consoled",
	"Consoles",
	"Consomme",
	"Conspire",
	"Constant",
	"Construe",
	"Consular",
	"Consumer",
	"Contacts",
	"Contagia",
	"Containd",
	"Contaminate",
	"Contender",
	"Contends",
	"Contents",
	"Contest",
	"Contexts",
	"Contours",
	"Contract",
	"Contrary",
	"Contrast",
	"Contrite",
	"Contrive",
	"Control",
	"Convents",
	"Converge",
	"Converse",
	"Convert",
	"Convexly",
	"Convince",
	"Convoys",
	"Conyeyed",
	"Cooldown",
	"Coppered",
	"Copybook",
	"Copyright",
	"Cordials",
	"Cordless",
	"Cordoned",
	"Coriander",
	"Corkages",
	"Corncobs",
	"Coronary",
	"Corridor",
	"Corrupts",
	"Corsages",
	"Cortexes",
	"Cosigner",
	"Cosmetics",
	"Costumed",
	"Costumer",
	"Cottages",
	"Couldest",
	"Coulters",
	"Councils",
	"Counters",
	"Counties",
	"Coupling",
	"Courage",
	"Couriers",
	"Courting",
	"Cousins",
	"Coverage",
	"Cowbirds",
	"Cowgirls",
	"Cowering",
	"Coworker",
	"Cracking",
	"Crackled",
	"Crackles",
	"Cradling",
	"Crafters",
	"Craftily",
	"Cragsman",
	"Crannies",
	"Crashing",
	"Crassest",
	"Cravings",
	"Crawlers",
	"Crawling",
	"Crayfish",
	"Crayoned",
	"Crazedly",
	"Creaking",
	"Creamery",
	"Creasing",
	"Creaters",
	"Creating",
	"Creation",
	"Creative",
	"Creatures",
	"Credible",
	"Creditry",
	"Credited",
	"Cremated",
	"Creeping",
	"Creodont",
	"Creosote",
	"Cresting",
	"Crevasse",
	"Criminal",
	"Crimping",
	"Cringing",
	"Crinkled",
	"Crisping",
	"Crissing",
	"Crispate",
	"Crispily",
	"Crisping",
	"Crissies",
	"Criteria",
	"Critique",
	"Croakers",
	"Croaking",
	"Crochets",
	"Crooning",
	"Cropless",
	"Crossbow",
	"Crosscut",
	"Crossing",
	"Crossway",
	"Crouched",
	"Crowbars",
	"Crowners",
	"Cruelest",
	"Cruisers",
	"Cruising",
	"Crunched",
	"Crunches",
	"Crusades",
	"Crushful",
	"Crustace",
	"Crusting",
	"Cryogens",
	"Cryptids",
	"Cubicles",
	"Cucumber",
	"Cudgels",
	"Culinary",
	"Culottes",
	"Cultures",
	"Cupboard",
	"Cupcakes",
	"Curating",
	"Curative",
	"Curators",
	"Curbside",
	"Currencies",
	"Cursored",
	"Curtains",
	"Cuspides",
	"Custodes",
	"Custodys",
	"Cutbacks",
	"Cuteness",
	"Cuticles",
	"Cutthroat",
	"Cynicism",
	"Cynosure",
	"Cystitis",
	"Dabblers",
	"Dabbling",
	"Daintier",
	"Dallying",
	"Damaging",
	"Damnable",
	"Damndest",
	"Damozels",
	"Dampness",
	"Dandered",
	"Dangered",
	"Danseuse",
	"Darkling",
	"Dartling",
	"Dashings",
	"Dateline",
	"Daughter",
	"Daybreak",
	"Daydream",
	"Daylight",
	"Dazzling",
	"Deadened",
	"Deadhead",
	"Deadlier",
	"Deadline",
	"Deadlock",
	"Deafened",
	"Dealership",
	"Debarked"
	};
};
